version: '3.6'

volumes:
  unite-cms:
    external: true
  unite-mysql:
    external: true
  unite-minio:
    external: true

services:

  unitecms-mysql:
    image: centos/mysql-57-centos7
    container_name: unitecms-mysql
    restart: always
    environment:
    - MYSQL_USER=${DATABASE_USER}
    - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    - MYSQL_DATABASE=${DATABASE_NAME}
    - MYSQL_ROOT_PASSWORD=fnSmWfFKu4aS5Sap7ydhsEW4TwaqpB
    ports:
    - "3307:3306"
    volumes:
    - unite-mysql:/var/lib/mysql

  unitecms-web:
    image: iiasa.azurecr.io/unitecmsdocker
    build: ./.docker/unite-cms
    container_name: unitecms-web
    working_dir: /app/unite-cms
    restart: always
    depends_on:
    - unitecms-mysql
    environment:
    - ROUTING_APPROACH=${ROUTING_APPROACH}
    - DEFAULT_HOSTNAME=${DEFAULT_HOSTNAME}
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_HOST=unitecms-mysql
    - DATABASE_PORT=3306
    - APP_ENV=${APP_ENV}
    - APP_SECRET=${APP_SECRET}
    - LOCALE_DEFAULT=${LOCALE_DEFAULT}
    - MAILER_SENDER=${MAILER_SENDER}
    - MAILER_URL=${MAILER_URL}
    volumes:
    - "/Users/karner/Documents/Projects/sandbox/unite-cms:/app/unite-cms"
    ports:
    - "8082:8080"

  unitecms-minio:
    image: minio/minio
    container_name: unitecms-minio
    restart: always
    ports:
    - "9009:9000"
    volumes:
    - unite-minio:/data
    environment:
    - "MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}"
    - "MINIO_SECRET_KEY=${MINIO_SECRET_KEY}"
    command: server /data
